#!/usr/bin/env sage
#
# CryptoHack -- Diffie-Hellman / Misc -- "Matrix revolutions"
#
# Setting: DH in the group generated by G in GL(150, GF(2)); private
# exponents are 149-bit primes, the shared secret G^(ab) keys AES-CBC.
#
# Attack:
#   charpoly(G) = f61 * f89 with f61, f89 irreducible and coprime, so the
#   minimal polynomial is squarefree and
#
#       GF(2)[G]  ~=  GF(2)[x]/f61  x  GF(2)[x]/f89  =  GF(2^61) x GF(2^89).
#
#   Under that isomorphism G corresponds to (x mod f61, x mod f89) and the
#   matrix DLP splits into two finite-field DLPs.  Both 2^61-1 and 2^89-1 are
#   Mersenne *primes*, so x generates each multiplicative group, and PARI's
#   fflog (index calculus in small characteristic) solves each in under a
#   second.  CRT recombines:
#
#       (2^61-1)(2^89-1) = 2^150 - 2^89 - 2^61 + 1 > 2^149 > A_priv,
#
#   so a single CRT lift already gives the exact private exponent.
#
#   Concretely, to move a matrix M in GF(2)[G] into GF(2^d) = GF(2)[x]/f:
#   take 0 != u in ker f(G); since f is the minimal polynomial of G on that
#   invariant subspace, (u, Gu, ..., G^(d-1)u) is a basis of it, and writing
#   M*u = sum c_i G^i u gives M|_ker  <->  sum c_i x^i.

from sage.all import *
from Crypto.Cipher import AES
from Crypto.Hash import SHA256
from Crypto.Util.Padding import unpad
import json, os

P = 2
N = 150
HERE = os.path.dirname(os.path.abspath(__file__))


def load_matrix(fname):
    data = open(os.path.join(HERE, fname), 'r').read().strip()
    rows = [list(map(int, row)) for row in data.splitlines()]
    return Matrix(GF(P), rows)


def derive_aes_key(M):
    # identical to the challenge's derive_aes_key: row-major '0'/'1' string
    mat_str = ''.join(str(x) for row in M for x in row)
    return SHA256.new(data=mat_str.encode()).digest()[:128]


def component_log(G, H, f):
    """
    Discrete log of H = G^e restricted to the G-invariant subspace ker f(G),
    where f is an irreducible factor of charpoly(G) of degree d.
    Returns e mod (2^d - 1).
    """
    d = f.degree()
    V = kernel(f(G).transpose())          # right kernel of f(G)
    assert V.dimension() == d
    u = V.basis()[0]

    # basis (u, Gu, ..., G^(d-1)u) of ker f(G)
    cols, v = [], u
    for _ in range(d):
        cols.append(v)
        v = G * v
    U = Matrix(GF(P), cols).transpose()
    assert U.rank() == d

    K = GF(2 ** d, 'x', modulus=f)
    x = K.gen()

    def to_field(M):
        c = U.solve_right(M * u)
        return sum(K(c[i]) * x ** i for i in range(d))

    return to_field(H).log(x)


G = load_matrix("generator.txt")
A_pub = load_matrix("alice.pub")
B_pub = load_matrix("bob.pub")

facs = [f for f, _ in G.charpoly().factor()]
print("[*] charpoly factors of degree:", [f.degree() for f in facs])

logs, mods = [], []
for f in facs:
    d = f.degree()
    e = component_log(G, A_pub, f)
    print("[+] a mod (2^%d - 1) = %d" % (d, e))
    logs.append(e)
    mods.append(2 ** d - 1)

a = crt(logs, mods)
print("[+] A_priv =", a)
print("[*] bit length:", a.nbits(), "| prime:", is_prime(a))
assert G ** a == A_pub, "recovered exponent does not reproduce alice.pub"
print("[*] check passed: G^a == A_pub")

shared_secret = B_pub ** a
key = derive_aes_key(shared_secret)

enc = json.load(open(os.path.join(HERE, "flag.enc")))
cipher = AES.new(key, AES.MODE_CBC, bytes.fromhex(enc["iv"]))
flag = unpad(cipher.decrypt(bytes.fromhex(enc["ciphertext"])), 16)
print("[+] FLAG:", flag.decode())
