#!/usr/bin/env sage
"""
CryptoHack :: Isogenies :: "CSIDH Key Exchange" (90)

Implement CSIDH-512 end to end: derive both public keys from the given private
exponent vectors, complete the exchange from each side, check the two shared
secrets agree, and decrypt the flag.

The protocol
------------
Public parameters: the odd primes l_0..l_73, p = 4 * prod(l_i) - 1, and the
starting curve E0 : y^2 = x^3 + x, i.e. M_0.

A private key is an exponent vector e in [-3,3]^74, denoting the ideal class
[l_0]^{e_0} ... [l_73]^{e_73}.  A public key is the single Montgomery
coefficient A of the curve that class sends E0 to.

    Alice:  A_pub = a * E0          Bob:  B_pub = b * E0
    Alice:  a * B_pub               Bob:  b * A_pub

and because the class group is abelian both sides land on (a+b) * E0.  The
shared secret is that curve's Montgomery coefficient.

Note how much smaller this is than SIDH: a public key is one element of F_p,
about 64 bytes, and *nothing else* is transmitted.  No torsion point images --
which is exactly why the 2022 attacks that destroyed SIDH do not apply.  The
price is speed and a subtler quantum security story (Kuperberg's algorithm
gives a subexponential quantum attack on the abelian hidden-shift problem, so
CSIDH parameters must be chosen far more conservatively than SIDH's were).

Recovering the Montgomery coefficient
-------------------------------------
Velu hands back a curve in some Weierstrass model; CSIDH needs the Montgomery
coefficient.  Brute-forcing A (fine at p = 419 in the earlier challenges) is
hopeless at 511 bits, so we invert the transformation properly.

M_A : y^2 = x^3 + Ax^2 + x becomes, under x -> x - A/3,

    y^2 = x^3 + (1 - A^2/3) x + (2A^3/27 - A/3),

and the Montgomery point x_M = 0 (the rational 2-torsion point) maps to
x_W = A/3.  So given E : y^2 = x^3 + ax + b with rational 2-torsion (alpha, 0),

    A = 3*alpha / sqrt(3*alpha^2 + a).

This is invariant under the Weierstrass scaling (a,b) -> (u^4 a, u^6 b), since
alpha -> u^2 alpha and sqrt(3 alpha^2 + a) -> u^2 sqrt(...), so it may be
applied to any short Weierstrass model of E.  Two cautions, both of which bit
during development:

  * E.a4()/E.a6() are NOT the short-Weierstrass coefficients when a2 != 0, and
    a Montgomery curve has a2 = A.  Take E.short_weierstrass_model() first.
  * sqrt is defined only up to sign, and the two signs give A and -A, which are
    quadratic twists and genuinely different CSIDH curves.  Pick the sign by
    testing which one is F_p-isomorphic to E.

Since E(F_p) is cyclic of order p+1 = 4*prod(l_i), its 2-torsion is Z/2: there
is exactly one rational alpha, so the recovered A is unique.
"""


# This file was *autogenerated* from the file solve_csidh.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_41 = Integer(41); _sage_const_43 = Integer(43); _sage_const_47 = Integer(47); _sage_const_53 = Integer(53); _sage_const_59 = Integer(59); _sage_const_61 = Integer(61); _sage_const_67 = Integer(67); _sage_const_71 = Integer(71); _sage_const_73 = Integer(73); _sage_const_79 = Integer(79); _sage_const_83 = Integer(83); _sage_const_89 = Integer(89); _sage_const_97 = Integer(97); _sage_const_101 = Integer(101); _sage_const_103 = Integer(103); _sage_const_107 = Integer(107); _sage_const_109 = Integer(109); _sage_const_113 = Integer(113); _sage_const_127 = Integer(127); _sage_const_131 = Integer(131); _sage_const_137 = Integer(137); _sage_const_139 = Integer(139); _sage_const_149 = Integer(149); _sage_const_151 = Integer(151); _sage_const_157 = Integer(157); _sage_const_163 = Integer(163); _sage_const_167 = Integer(167); _sage_const_173 = Integer(173); _sage_const_179 = Integer(179); _sage_const_181 = Integer(181); _sage_const_191 = Integer(191); _sage_const_193 = Integer(193); _sage_const_197 = Integer(197); _sage_const_199 = Integer(199); _sage_const_211 = Integer(211); _sage_const_223 = Integer(223); _sage_const_227 = Integer(227); _sage_const_229 = Integer(229); _sage_const_233 = Integer(233); _sage_const_239 = Integer(239); _sage_const_241 = Integer(241); _sage_const_251 = Integer(251); _sage_const_257 = Integer(257); _sage_const_263 = Integer(263); _sage_const_269 = Integer(269); _sage_const_271 = Integer(271); _sage_const_277 = Integer(277); _sage_const_281 = Integer(281); _sage_const_283 = Integer(283); _sage_const_293 = Integer(293); _sage_const_307 = Integer(307); _sage_const_311 = Integer(311); _sage_const_313 = Integer(313); _sage_const_317 = Integer(317); _sage_const_331 = Integer(331); _sage_const_337 = Integer(337); _sage_const_347 = Integer(347); _sage_const_349 = Integer(349); _sage_const_353 = Integer(353); _sage_const_359 = Integer(359); _sage_const_367 = Integer(367); _sage_const_373 = Integer(373); _sage_const_587 = Integer(587); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_74 = Integer(74); _sage_const_25 = Integer(25); _sage_const_128 = Integer(128); _sage_const_16 = Integer(16)
import time
from Crypto.Cipher import AES
from Crypto.Hash import SHA256
from Crypto.Util.Padding import unpad

# ---------------------------------------------------------------------------
# Parameters (verbatim from source_csidh.sage)
# ---------------------------------------------------------------------------

ells = [_sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_11 , _sage_const_13 , _sage_const_17 , _sage_const_19 , _sage_const_23 , _sage_const_29 , _sage_const_31 , _sage_const_37 , _sage_const_41 , _sage_const_43 , _sage_const_47 , _sage_const_53 , _sage_const_59 , _sage_const_61 , _sage_const_67 ,
        _sage_const_71 , _sage_const_73 , _sage_const_79 , _sage_const_83 , _sage_const_89 , _sage_const_97 , _sage_const_101 , _sage_const_103 , _sage_const_107 , _sage_const_109 , _sage_const_113 , _sage_const_127 , _sage_const_131 , _sage_const_137 , _sage_const_139 ,
        _sage_const_149 , _sage_const_151 , _sage_const_157 , _sage_const_163 , _sage_const_167 , _sage_const_173 , _sage_const_179 , _sage_const_181 , _sage_const_191 , _sage_const_193 , _sage_const_197 , _sage_const_199 , _sage_const_211 , _sage_const_223 ,
        _sage_const_227 , _sage_const_229 , _sage_const_233 , _sage_const_239 , _sage_const_241 , _sage_const_251 , _sage_const_257 , _sage_const_263 , _sage_const_269 , _sage_const_271 , _sage_const_277 , _sage_const_281 , _sage_const_283 , _sage_const_293 ,
        _sage_const_307 , _sage_const_311 , _sage_const_313 , _sage_const_317 , _sage_const_331 , _sage_const_337 , _sage_const_347 , _sage_const_349 , _sage_const_353 , _sage_const_359 , _sage_const_367 , _sage_const_373 , _sage_const_587 ]
p = _sage_const_4  * prod(ells) - _sage_const_1 
F = GF(p)
E0 = EllipticCurve(F, [_sage_const_1 , _sage_const_0 ])                    # M_0

a_priv = [-_sage_const_1 , -_sage_const_2 , -_sage_const_3 , -_sage_const_3 , -_sage_const_2 , -_sage_const_3 , -_sage_const_3 , _sage_const_0 , _sage_const_2 , -_sage_const_1 , _sage_const_2 , -_sage_const_1 , -_sage_const_2 , -_sage_const_3 , _sage_const_1 , _sage_const_2 , _sage_const_1 , _sage_const_2 , _sage_const_0 , _sage_const_0 , _sage_const_1 , -_sage_const_1 , _sage_const_0 , _sage_const_2 , -_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 , -_sage_const_1 , -_sage_const_3 , _sage_const_1 , -_sage_const_1 , -_sage_const_3 , -_sage_const_3 , _sage_const_2 , _sage_const_2 , _sage_const_1 , -_sage_const_1 , -_sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_1 , -_sage_const_2 , _sage_const_2 , _sage_const_2 , -_sage_const_2 , -_sage_const_2 , _sage_const_0 , _sage_const_0 , _sage_const_2 , _sage_const_0 , -_sage_const_1 , -_sage_const_3 , -_sage_const_2 , -_sage_const_2 , _sage_const_0 , -_sage_const_1 , -_sage_const_3 , -_sage_const_1 , -_sage_const_2 , -_sage_const_3 , -_sage_const_2 , _sage_const_2 , _sage_const_1 , _sage_const_1 , -_sage_const_2 , _sage_const_0 , _sage_const_1 , -_sage_const_1 , -_sage_const_3 , _sage_const_2 ]
b_priv = [-_sage_const_1 , -_sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_2 , _sage_const_0 , _sage_const_2 , -_sage_const_1 , -_sage_const_3 , _sage_const_1 , _sage_const_0 , -_sage_const_2 , -_sage_const_2 , _sage_const_2 , -_sage_const_1 , -_sage_const_2 , -_sage_const_3 , -_sage_const_3 , -_sage_const_3 , _sage_const_2 , _sage_const_2 , _sage_const_2 , -_sage_const_2 , -_sage_const_1 , _sage_const_1 , -_sage_const_2 , _sage_const_0 , -_sage_const_3 , -_sage_const_1 , _sage_const_1 , -_sage_const_1 , -_sage_const_1 , -_sage_const_3 , -_sage_const_1 , -_sage_const_2 , _sage_const_1 , -_sage_const_1 , -_sage_const_2 , -_sage_const_3 , _sage_const_1 , _sage_const_0 , -_sage_const_1 , _sage_const_1 , _sage_const_2 , _sage_const_2 , _sage_const_0 , _sage_const_0 , -_sage_const_1 , -_sage_const_2 , -_sage_const_2 , _sage_const_1 , -_sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 , -_sage_const_3 , -_sage_const_2 , -_sage_const_1 , _sage_const_2 , _sage_const_0 , -_sage_const_3 , -_sage_const_2 , _sage_const_1 , _sage_const_1 , -_sage_const_2 , -_sage_const_1 , -_sage_const_1 , _sage_const_2 , _sage_const_0 , _sage_const_1 ]

iv_hex = 'daf6cd181775664b099609789fb564c9'
ct_hex = '3dd92e255c8e677f4a92226d09f56e2b2f567052ffd4f6f60200018454a83affc2e694c2bf2ad27da38f7f49b6e89928'

assert is_prime(p) and p % _sage_const_4  == _sage_const_3 
assert E0.is_supersingular() and E0.order() == p + _sage_const_1 
assert E0.abelian_group().invariants() == (p + _sage_const_1 ,), "E0(F_p) must be cyclic"
assert not F(-_sage_const_1 ).is_square()
assert len(ells) == len(a_priv) == len(b_priv) == _sage_const_74 

print(f"CSIDH-512:  p has {p.nbits()} bits,  {len(ells)} primes")
print(f"  |a| = {sum(abs(e) for e in a_priv)} steps,  "
      f"|b| = {sum(abs(e) for e in b_priv)} steps\n")

Rx = PolynomialRing(F, 'x')
x = Rx.gen()


# ---------------------------------------------------------------------------
# Montgomery bookkeeping
# ---------------------------------------------------------------------------

def curve(A):
    return EllipticCurve(F, [_sage_const_0 , A, _sage_const_0 , _sage_const_1 , _sage_const_0 ])     # M_A : y^2 = x^3 + Ax^2 + x


def montgomery_A(E):
    """The unique A with M_A isomorphic to E over F_p."""
    Es = E.short_weierstrass_model()
    a, b = Es.a4(), Es.a6()
    for alpha in (x**_sage_const_3  + a * x + b).roots(F, multiplicities=False):
        t = _sage_const_3  * alpha**_sage_const_2  + a
        if not t.is_square():
            continue
        A = _sage_const_3  * alpha / t.sqrt()
        for cand in (A, -A):                     # the two signs are twists
            if E.is_isomorphic(curve(cand)):
                return cand
    raise ValueError("no Montgomery coefficient found")


assert montgomery_A(E0) == _sage_const_0 


# ---------------------------------------------------------------------------
# The group action
# ---------------------------------------------------------------------------

def step(A, ell):
    """Forward: the unique F_p-rational ell-isogeny.  This is the action of [l]."""
    E = curve(A)
    cofactor = (p + _sage_const_1 ) // ell
    while True:
        P = cofactor * E.random_point()
        if P.order() == ell:
            break
    phi = E.isogeny(P)
    assert phi.degree() == ell
    return montgomery_A(phi.codomain())


def back_step(A, ell):
    """Backward: the action of [lbar] = [l]^-1, via the twist (M_A)^t = M_-A."""
    return -step(-A, ell)


def group_action(A, evec, label=""):
    """Apply [l_0]^e_0 ... [l_k]^e_k to M_A."""
    t0 = time.time()
    total = sum(abs(e) for e in evec)
    done = _sage_const_0 
    for ell, e in zip(ells, evec):
        for _ in range(abs(e)):
            A = step(A, ell) if e > _sage_const_0  else back_step(A, ell)
            done += _sage_const_1 
            if done % _sage_const_25  == _sage_const_0 :
                print(f"    [{label}] {done}/{total} steps  ({time.time()-t0:.0f}s)",
                      flush=True)
    print(f"    [{label}] done, {total} steps in {time.time()-t0:.0f}s", flush=True)
    return A


# ---------------------------------------------------------------------------
# Key exchange
# ---------------------------------------------------------------------------

print("[*] Alice's public key ...")
A_pub = group_action(F(_sage_const_0 ), a_priv, "alice pub")
print(f"    A_pub = {A_pub}\n")

print("[*] Bob's public key ...")
B_pub = group_action(F(_sage_const_0 ), b_priv, "bob pub")
print(f"    B_pub = {B_pub}\n")

print("[*] Alice applies her key to Bob's curve ...")
sec_a = group_action(B_pub, a_priv, "alice sec")
print("[*] Bob applies his key to Alice's curve ...")
sec_b = group_action(A_pub, b_priv, "bob sec")

print(f"\n  Alice's shared secret : {sec_a}")
print(f"  Bob's shared secret   : {sec_b}")
assert sec_a == sec_b, "the two sides disagree -- the action did not commute"
print("  [ok] both parties agree")

# The challenge's own phrasing: the result is the action of the SUM of the
# two exponent vectors applied to E0.  Verified independently.
print("\n[*] cross-check: acting with (a + b) directly on E0 ...")
sec_sum = group_action(F(_sage_const_0 ), [ea + eb for ea, eb in zip(a_priv, b_priv)], "a+b")
assert sec_sum == sec_a, "(a+b)*E0 differs from a*(b*E0)"
print("  [ok] (a + b) * E0 equals a * (b * E0)")

shared_secret = sec_a


# ---------------------------------------------------------------------------
# Decrypt
# ---------------------------------------------------------------------------

key = SHA256.new(data=str(shared_secret).encode()).digest()[:_sage_const_128 ]
flag = unpad(AES.new(key, AES.MODE_CBC, bytes.fromhex(iv_hex)).decrypt(bytes.fromhex(ct_hex)), _sage_const_16 )

print()
print(f"FLAG = {flag.decode()}")

