#!/usr/bin/env sage
"""
CryptoHack :: Isogenies :: "Twisted CSIDH Isogenies" (70)

E0 : y^2 = x^3 + x over F_419.  Walk one step *backwards* on the 3-isogeny
graph.  Report the Montgomery coefficient A.

The problem
-----------
The F_p-rational l-torsion gives exactly one l-isogeny out of each curve, and
it always moves the same way round the cycle: it is the action of [l].  To
undo it you need [l]^{-1} = [lbar], the conjugate ideal, and there is no
rational l-torsion point that hands it to you.  Walking forward h-1 times would
work and is useless -- real CSIDH keys have exponents like -5 and the whole
point is that a backward step costs the same as a forward one.

The twist trick
---------------
For p = 3 mod 4 the quadratic twist of a Montgomery curve is simply

    (M_A)^t  =  M_{-A}.

Derivation: twisting M_A : y^2 = x^3 + Ax^2 + x by a non-residue d means
d*y^2 = x^3 + Ax^2 + x.  Substituting x -> u*X, y -> v*Y and demanding the
Montgomery shape back forces u^3/(d v^2) = 1 and u/(d v^2) = 1, hence u^2 = 1.
Taking u = -1 gives d v^2 = -1, which is solvable precisely because -1 is a
non-residue when p = 3 mod 4, and then the x^2 coefficient becomes

    A' = A u^2 / (d v^2) = -A.

Twisting conjugates the class group action: Frobenius acts on the twist with
the opposite sign, so [l] on E^t corresponds to [lbar] on E.  Therefore

    backward_l(A)  =  - forward_l( -A )

-- twist, step forward, twist back.  Three cheap operations, no dependence on
the class number.

A pleasant special case: E0 has A = 0, and -0 = 0, so **E0 is its own quadratic
twist**.  That self-duality is one reason A = 0 is the standard CSIDH starting
curve: it is the fixed point of the twisting involution.

Implementation note (not needed at this size).  Real CSIDH never forms the
twist explicitly.  Working with x-only arithmetic, a random x either satisfies
"x^3 + Ax^2 + x is a square", giving a point on the curve, or it does not,
giving a point on the twist.  So one simply tests quadratic residuosity of
x^3 + Ax^2 + x and thereby gets a forward or a backward step for free, which is
why CSIDH's positive and negative exponents cost exactly the same.
"""


# This file was *autogenerated* from the file solve_twisted_csidh.sage
from sage.all_cmdline import *   # import sage library

_sage_const_419 = Integer(419); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_75 = Integer(75); _sage_const_158 = Integer(158); _sage_const_261 = Integer(261); _sage_const_404 = Integer(404); _sage_const_7 = Integer(7)
p = _sage_const_419 
F = GF(p)
ell = _sage_const_3 

E0 = EllipticCurve(F, [_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ])          # M_0
assert p % _sage_const_4  == _sage_const_3  and E0.is_supersingular() and E0.order() == p + _sage_const_1 
assert not F(-_sage_const_1 ).is_square(), "-1 must be a non-residue for the twist formula"


def montgomery_A(E):
    As = [A for A in F
          if A**_sage_const_2  != _sage_const_4  and EllipticCurve(F, [_sage_const_0 , A, _sage_const_0 , _sage_const_1 , _sage_const_0 ]).is_isomorphic(E)]
    assert len(As) == _sage_const_1 , f"expected a unique Montgomery coefficient, got {As}"
    return As[_sage_const_0 ]


def curve(A):
    return EllipticCurve(F, [_sage_const_0 , A, _sage_const_0 , _sage_const_1 , _sage_const_0 ])


def step(A, l):
    """Forward: the unique F_p-rational l-isogeny.  This is the action of [l]."""
    E = curve(A)
    cofactor = (p + _sage_const_1 ) // l
    while True:
        R = cofactor * E.random_point()
        if R.order() == l:
            break
    phi = E.isogeny(R)
    assert phi.degree() == l
    return montgomery_A(phi.codomain())


def back_step(A, l):
    """Backward: the action of [lbar] = [l]^{-1}, via the quadratic twist."""
    return -step(-A, l)


# --- the twist formula itself, checked rather than trusted ----------------
d = F(next(t for t in range(_sage_const_2 , p) if not F(t).is_square()))       # a non-residue
for A in [F(_sage_const_0 ), F(_sage_const_75 ), F(_sage_const_158 ), F(_sage_const_261 ), F(_sage_const_404 )]:
    assert curve(A).quadratic_twist(d).is_isomorphic(curve(-A)),         f"(M_{A})^t is not M_{-A}"
print(f"[ok] (M_A)^t = M_(-A) verified for several A   (non-residue d = {d})")
print(f"[ok] E0 is its own twist: -0 = 0\n")


# ---------------------------------------------------------------------------
# One step backwards on the 3-isogeny graph
# ---------------------------------------------------------------------------

A_fwd = step(F(_sage_const_0 ), ell)
A_back = back_step(F(_sage_const_0 ), ell)
print(f"forward  [l_{ell}]      * E0 : A = {A_fwd}")
print(f"backward [l_{ell}]^(-1) * E0 : A = {A_back}")
assert A_fwd != A_back, "forward and backward gave the same curve"

# Decisive check: stepping forward from the backward result must return to E0.
assert step(A_back, ell) == _sage_const_0 , "forward(backward(E0)) != E0"
print(f"[ok] one forward {ell}-isogeny from A = {A_back} returns to A = 0")

# and symmetrically
assert back_step(A_fwd, ell) == _sage_const_0 
print(f"[ok] one backward {ell}-isogeny from A = {A_fwd} returns to A = 0")


# ---------------------------------------------------------------------------
# Independent check through the class group
# ---------------------------------------------------------------------------

cycle = [F(_sage_const_0 )]
while True:
    cycle.append(step(cycle[-_sage_const_1 ], _sage_const_7 ))
    if cycle[-_sage_const_1 ] == _sage_const_0 :
        cycle.pop()
        break
h = len(cycle)
k3 = cycle.index(A_fwd)
print(f"\nclass group: h = {h},  [l_{ell}] = [l_7]^{k3}")
print(f"  so [l_{ell}]^(-1) = [l_7]^{(-k3) % h},  giving A = {cycle[(-k3) % h]}")
assert cycle[(-k3) % h] == A_back, "class-group prediction disagrees"
print("[ok] class-group prediction matches the twist computation")

print()
print(f"FLAG (Montgomery coefficient A) = {A_back}")

