#!/usr/bin/env sage
"""
CryptoHack :: Isogenies :: "SIDH Key Exchange" (80)

Fill in gen_public_key / gen_shared_secret from source_sidh.sage, derive the
shared secret, and decrypt the flag.

The protocol
------------
Public parameters: a supersingular curve E0 / F_{p^2} with p = 2^ea * 3^eb - 1,
and bases of the two torsion subgroups,

    E0[2^ea] = <P2, Q2>,      E0[3^eb] = <P3, Q3>.

Because #E0(F_{p^2}) = (p+1)^2 = (2^ea 3^eb)^2, both full torsion subgroups are
F_{p^2}-rational -- that is the entire reason this prime shape is chosen.

    Alice:  KA = P2 + [sA] Q2   (order 2^ea)   phiA : E0 -> EA = E0/<KA>
            publishes  EA, phiA(P3), phiA(Q3)
    Bob:    KB = P3 + [sB] Q3   (order 3^eb)   phiB : E0 -> EB = E0/<KB>
            publishes  EB, phiB(P2), phiB(Q2)

    Alice:  E_SA = EB / < phiB(P2) + [sA] phiB(Q2) >
    Bob:    E_SB = EA / < phiA(P3) + [sB] phiA(Q3) >

    shared secret = j(E_SA) = j(E_SB)

Why the two sides agree
-----------------------
Alice's second step has kernel generated by phiB(KA), so composing gives an
isogeny E0 -> E_SA with kernel <KA, KB>; symmetrically for Bob.  Both sides
therefore compute E0/<KA, KB>, up to isomorphism -- and the j-invariant is
exactly the isomorphism invariant, which is why the secret is j and not the
curve coefficients.  This is the "isogeny square": the two paths around the
square commute.

Note what makes it work: Alice cannot evaluate phiB, so Bob must hand her the
images of the 2-torsion basis under phiB.  Publishing those torsion images is
the whole convenience of SIDH -- and, as the next challenge shows, exactly the
extra structure that the SIDH break (Castryck-Decru / Maino-Martindale, 2022)
feeds on.  Plain isogeny problems are not known to be broken; SIDH's torsion
point information is what fell.

Everything below reuses the chained Velu machinery from Composite Isogenies,
extended so that each step also pushes a list of auxiliary points forward.
"""


# This file was *autogenerated* from the file solve_sidh.sage
from sage.all_cmdline import *   # import sage library

_sage_const_110 = Integer(110); _sage_const_67 = Integer(67); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_118242575052254473701407051403380184157502700009529430046122822477 = Integer(118242575052254473701407051403380184157502700009529430046122822477); _sage_const_57638278144985143549644316704182130279784191379170896458696787312 = Integer(57638278144985143549644316704182130279784191379170896458696787312); _sage_const_80915735815367072410310689908590367651933218830435520913424043510 = Integer(80915735815367072410310689908590367651933218830435520913424043510); _sage_const_35228327576503752484578273317308597612913304063200715424014549037 = Integer(35228327576503752484578273317308597612913304063200715424014549037); _sage_const_27856673727210297071672501895829918842041821446996051944738115273 = Integer(27856673727210297071672501895829918842041821446996051944738115273); _sage_const_101349537690838191347553037323956940169953967852439843389873653018 = Integer(101349537690838191347553037323956940169953967852439843389873653018); _sage_const_45955772915614774101614751673022340983778200451506382887743008335 = Integer(45955772915614774101614751673022340983778200451506382887743008335); _sage_const_76499786039494489791183573966490259392789635716963920208794989512 = Integer(76499786039494489791183573966490259392789635716963920208794989512); _sage_const_68702305424425607424554396971378391833152415806389206440833676844 = Integer(68702305424425607424554396971378391833152415806389206440833676844); _sage_const_63162905189208938201083385603424075109355856156240516441321158383 = Integer(63162905189208938201083385603424075109355856156240516441321158383); _sage_const_14452401602439328239712793251073780692192036710425129093829067649 = Integer(14452401602439328239712793251073780692192036710425129093829067649); _sage_const_110903430163815016394569999096524527007769669322432532390635606190 = Integer(110903430163815016394569999096524527007769669322432532390635606190); _sage_const_50967992419888058158544483269655763559879646024537212566396940681 = Integer(50967992419888058158544483269655763559879646024537212566396940681); _sage_const_39165103284419354968504615023980382940222714919046676966425620242 = Integer(39165103284419354968504615023980382940222714919046676966425620242); _sage_const_113476160032430656302485251779124302915433268423829474022852380544 = Integer(113476160032430656302485251779124302915433268423829474022852380544); _sage_const_74814862075401178218909769629701747112662266906635780085603780902 = Integer(74814862075401178218909769629701747112662266906635780085603780902); _sage_const_225902606209514408534212339057054 = Integer(225902606209514408534212339057054); _sage_const_38410379124791756271891302485727 = Integer(38410379124791756271891302485727); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_74 = Integer(74); _sage_const_128 = Integer(128); _sage_const_16 = Integer(16)
from Crypto.Cipher import AES
from Crypto.Hash import SHA256
from Crypto.Util.Padding import unpad

# ---------------------------------------------------------------------------
# Public parameters (verbatim from source_sidh.sage)
# ---------------------------------------------------------------------------

ea, eb = _sage_const_110 , _sage_const_67 
p = _sage_const_2 **ea * _sage_const_3 **eb - _sage_const_1 
assert is_prime(p) and p % _sage_const_4  == _sage_const_3 

F = GF(p**_sage_const_2 , names="i", modulus=[_sage_const_1 , _sage_const_0 , _sage_const_1 ])
i = F.gen()

E0 = EllipticCurve(F, [_sage_const_1 , _sage_const_0 ])

P2 = E0(_sage_const_118242575052254473701407051403380184157502700009529430046122822477 *i + _sage_const_57638278144985143549644316704182130279784191379170896458696787312 ,
        _sage_const_80915735815367072410310689908590367651933218830435520913424043510 *i + _sage_const_35228327576503752484578273317308597612913304063200715424014549037 )
Q2 = E0(_sage_const_27856673727210297071672501895829918842041821446996051944738115273 *i + _sage_const_101349537690838191347553037323956940169953967852439843389873653018 ,
        _sage_const_45955772915614774101614751673022340983778200451506382887743008335 *i + _sage_const_76499786039494489791183573966490259392789635716963920208794989512 )
P3 = E0(_sage_const_68702305424425607424554396971378391833152415806389206440833676844 *i + _sage_const_63162905189208938201083385603424075109355856156240516441321158383 ,
        _sage_const_14452401602439328239712793251073780692192036710425129093829067649 *i + _sage_const_110903430163815016394569999096524527007769669322432532390635606190 )
Q3 = E0(_sage_const_50967992419888058158544483269655763559879646024537212566396940681 *i + _sage_const_39165103284419354968504615023980382940222714919046676966425620242 ,
        _sage_const_113476160032430656302485251779124302915433268423829474022852380544 *i + _sage_const_74814862075401178218909769629701747112662266906635780085603780902 )

sA = _sage_const_225902606209514408534212339057054 
sB = _sage_const_38410379124791756271891302485727 

iv_hex = '05a4cfbce59acb952128af83c9694390'
ct_hex = '755b72b2e3bef2e7a4b2ce4a370f287ad04c1359bace25f3def8be23c0c49e89b4302408ad2dcb02d4875fe58c543d91'

# sanity: the bases really are bases of the claimed torsion subgroups
assert P2.order() == Q2.order() == _sage_const_2 **ea
assert P3.order() == Q3.order() == _sage_const_3 **eb
assert P2.weil_pairing(Q2, _sage_const_2 **ea).multiplicative_order() == _sage_const_2 **ea, "P2,Q2 not independent"
assert P3.weil_pairing(Q3, _sage_const_3 **eb).multiplicative_order() == _sage_const_3 **eb, "P3,Q3 not independent"


# ---------------------------------------------------------------------------
# Velu, with point evaluation  (see solve_composite_isogenies.sage)
# ---------------------------------------------------------------------------

def velu(E, T):
    """Separable isogeny phi : E -> E/<T>.  Returns (codomain, evaluate)."""
    a1, a2, a3, a4, a6 = E.a_invariants()
    assert (a1, a2, a3) == (_sage_const_0 , _sage_const_0 , _sage_const_0 ), "expected short Weierstrass form"
    Fld = E.base_field()
    O = E(_sage_const_0 )

    R, seen = [], set()
    Q = T
    while Q != O:
        if Q not in seen:
            R.append(Q)
            seen.add(Q)
            seen.add(-Q)
        Q = Q + T

    data = []
    v_sum = Fld(_sage_const_0 )
    w_sum = Fld(_sage_const_0 )
    for Q in R:
        xQ, yQ = Q.xy()
        gx = _sage_const_3  * xQ**_sage_const_2  + a4
        vQ = gx if yQ == _sage_const_0  else _sage_const_2  * gx       # 2-torsion is self-paired: no factor 2
        uQ = _sage_const_4  * yQ**_sage_const_2 
        data.append((xQ, uQ, vQ))
        v_sum += vQ
        w_sum += uQ + xQ * vQ

    Ecod = EllipticCurve(Fld, [a4 - _sage_const_5  * v_sum, a6 - _sage_const_7  * w_sum])
    kernel_x = {xQ for xQ, _, _ in data}

    def evaluate(P):
        if P == O:
            return Ecod(_sage_const_0 )
        x, y = P.xy()
        if x in kernel_x:
            return Ecod(_sage_const_0 )
        X = x
        dX = Fld(_sage_const_1 )
        for xQ, uQ, vQ in data:
            d = x - xQ
            d2 = d * d
            X += vQ / d + uQ / d2
            dX -= vQ / d2 + _sage_const_2  * uQ / (d2 * d)
        return Ecod(X, y * dX)               # Y = y * dX/dx (Velu is normalised)

    return Ecod, evaluate


def isogeny_chain(E, K, l, e, push=()):
    """
    Codomain of the degree l^e isogeny with kernel <K>, computed as e
    prime-degree steps.  Also pushes each point of `push` through the whole
    composition.  Returns (codomain, [images]).
    """
    assert K.order() == l**e, f"expected order {l}^{e}, got {factor(K.order())}"

    Ecur, Kcur = E, K
    pushed = list(push)
    for j in range(e):
        T = (l**(e - _sage_const_1  - j)) * Kcur
        assert T.order() == l

        Ecur, evaluate = velu(Ecur, T)
        pushed = [evaluate(X) for X in pushed]
        if j < e - _sage_const_1 :
            Kcur = evaluate(Kcur)
            assert Kcur.order() == l**(e - _sage_const_1  - j), "kernel order did not drop by l"

    return Ecur, pushed


# ---------------------------------------------------------------------------
# The two TODOs from source.sage
# ---------------------------------------------------------------------------

def gen_public_key(E, P, Q, s, l, e, push):
    """Secret s -> (codomain, images of the other party's torsion basis)."""
    K = P + s * Q
    return isogeny_chain(E, K, l, e, push=push)


def gen_shared_secret(E, imP, imQ, s, l, e):
    """Second leg: same secret s, applied to the received torsion images."""
    K = imP + s * imQ
    Ecod, _ = isogeny_chain(E, K, l, e)
    return Ecod.j_invariant()


print("=" * _sage_const_74 )
print("SIDH Key Exchange")
print("=" * _sage_const_74 )
print(f"  p  = 2^{ea} * 3^{eb} - 1")
print(f"  E0 : {E0}")
print()

# --- Alice: phiA : E0 -> EA, degree 2^ea, publishes images of the 3-torsion ---
EA, (imP3, imQ3) = gen_public_key(E0, P2, Q2, sA, _sage_const_2 , ea, push=[P3, Q3])
print(f"  Alice   EA : j = {EA.j_invariant()}")

# --- Bob: phiB : E0 -> EB, degree 3^eb, publishes images of the 2-torsion ---
EB, (imP2, imQ2) = gen_public_key(E0, P3, Q3, sB, _sage_const_3 , eb, push=[P2, Q2])
print(f"  Bob     EB : j = {EB.j_invariant()}")
print()

# --- second legs ---
jA = gen_shared_secret(EB, imP2, imQ2, sA, _sage_const_2 , ea)
jB = gen_shared_secret(EA, imP3, imQ3, sB, _sage_const_3 , eb)

print(f"  Alice   j(E_SA) = {jA}")
print(f"  Bob     j(E_SB) = {jB}")
assert jA == jB, "the two sides disagree -- the isogeny square did not commute"
print("  [ok] both parties agree on the shared secret")

shared_secret = jA


# ---------------------------------------------------------------------------
# Decrypt
# ---------------------------------------------------------------------------

key = SHA256.new(data=str(shared_secret).encode()).digest()[:_sage_const_128 ]
cipher = AES.new(key, AES.MODE_CBC, bytes.fromhex(iv_hex))
flag = unpad(cipher.decrypt(bytes.fromhex(ct_hex)), _sage_const_16 )

print()
print(f"FLAG = {flag.decode()}")

